# Generated by Django 4.1.1 on 2022-09-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("us_index_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("price", models.FloatField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="djitest", options={"managed": False, "ordering": ["-time"]},
        ),
        migrations.AlterModelOptions(
            name="ixictest", options={"managed": False, "ordering": ["-time"]},
        ),
        migrations.AlterModelOptions(
            name="ndxtest", options={"managed": False, "ordering": ["-time"]},
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_full_name", models.CharField(max_length=64)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CC", "Credit card"),
                            ("DC", "Debit card"),
                            ("ET", "Ethereum"),
                            ("BC", "Bitcoin"),
                        ],
                        default="CC",
                        max_length=2,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("successful", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="us_index_dashboard.item",
                    ),
                ),
            ],
            options={"ordering": ["-time"],},
        ),
    ]
